/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as dashboardRouteRouteImport } from './routes/(dashboard)/route'
import { Route as dashboardIndexRouteImport } from './routes/(dashboard)/index'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as dashboardViolationHistoryIndexRouteImport } from './routes/(dashboard)/violation-history/index'
import { Route as dashboardUserManagementIndexRouteImport } from './routes/(dashboard)/user-management/index'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardRouteRoute = dashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardIndexRoute = dashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => publicRouteRoute,
} as any)
const dashboardViolationHistoryIndexRoute =
  dashboardViolationHistoryIndexRouteImport.update({
    id: '/violation-history/',
    path: '/violation-history/',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardUserManagementIndexRoute =
  dashboardUserManagementIndexRouteImport.update({
    id: '/user-management/',
    path: '/user-management/',
    getParentRoute: () => dashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof publicLoginRoute
  '/': typeof dashboardIndexRoute
  '/user-management': typeof dashboardUserManagementIndexRoute
  '/violation-history': typeof dashboardViolationHistoryIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof publicLoginRoute
  '/': typeof dashboardIndexRoute
  '/user-management': typeof dashboardUserManagementIndexRoute
  '/violation-history': typeof dashboardViolationHistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(dashboard)': typeof dashboardRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(public)/login': typeof publicLoginRoute
  '/(dashboard)/': typeof dashboardIndexRoute
  '/(dashboard)/user-management/': typeof dashboardUserManagementIndexRoute
  '/(dashboard)/violation-history/': typeof dashboardViolationHistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/' | '/user-management' | '/violation-history'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/user-management' | '/violation-history'
  id:
    | '__root__'
    | '/(dashboard)'
    | '/(public)'
    | '/(public)/login'
    | '/(dashboard)/'
    | '/(dashboard)/user-management/'
    | '/(dashboard)/violation-history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  dashboardRouteRoute: typeof dashboardRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)': {
      id: '/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/': {
      id: '/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(dashboard)/violation-history/': {
      id: '/(dashboard)/violation-history/'
      path: '/violation-history'
      fullPath: '/violation-history'
      preLoaderRoute: typeof dashboardViolationHistoryIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/user-management/': {
      id: '/(dashboard)/user-management/'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof dashboardUserManagementIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
  }
}

interface dashboardRouteRouteChildren {
  dashboardIndexRoute: typeof dashboardIndexRoute
  dashboardUserManagementIndexRoute: typeof dashboardUserManagementIndexRoute
  dashboardViolationHistoryIndexRoute: typeof dashboardViolationHistoryIndexRoute
}

const dashboardRouteRouteChildren: dashboardRouteRouteChildren = {
  dashboardIndexRoute: dashboardIndexRoute,
  dashboardUserManagementIndexRoute: dashboardUserManagementIndexRoute,
  dashboardViolationHistoryIndexRoute: dashboardViolationHistoryIndexRoute,
}

const dashboardRouteRouteWithChildren = dashboardRouteRoute._addFileChildren(
  dashboardRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicLoginRoute: typeof publicLoginRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicLoginRoute: publicLoginRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  dashboardRouteRoute: dashboardRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
